name: SFTP Listing

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  list_sftp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install LFTP
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: List root folder on SFTP server
        run: |
          lftp -u ${{ secrets.SFTP_USERNAME }},${{ secrets.SFTP_PASSWORD }} -p 10022 sftp://${{ secrets.SFTP_HOST }} -e "ls; exit"